// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: chunkdata_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// To store the pass the chunkid we are looking for what Node contains it
type ChunkData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node    *Node  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Chunkid string `protobuf:"bytes,2,opt,name=chunkid,proto3" json:"chunkid,omitempty"`
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chunkdata_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_chunkdata_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_chunkdata_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkData) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ChunkData) GetChunkid() string {
	if x != nil {
		return x.Chunkid
	}
	return ""
}

var File_chunkdata_message_proto protoreflect.FileDescriptor

var file_chunkdata_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a,
	0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x69, 0x64, 0x42,
	0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chunkdata_message_proto_rawDescOnce sync.Once
	file_chunkdata_message_proto_rawDescData = file_chunkdata_message_proto_rawDesc
)

func file_chunkdata_message_proto_rawDescGZIP() []byte {
	file_chunkdata_message_proto_rawDescOnce.Do(func() {
		file_chunkdata_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_chunkdata_message_proto_rawDescData)
	})
	return file_chunkdata_message_proto_rawDescData
}

var file_chunkdata_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chunkdata_message_proto_goTypes = []interface{}{
	(*ChunkData)(nil), // 0: ChunkData
	(*Node)(nil),      // 1: Node
}
var file_chunkdata_message_proto_depIdxs = []int32{
	1, // 0: ChunkData.node:type_name -> Node
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chunkdata_message_proto_init() }
func file_chunkdata_message_proto_init() {
	if File_chunkdata_message_proto != nil {
		return
	}
	file_node_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chunkdata_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chunkdata_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chunkdata_message_proto_goTypes,
		DependencyIndexes: file_chunkdata_message_proto_depIdxs,
		MessageInfos:      file_chunkdata_message_proto_msgTypes,
	}.Build()
	File_chunkdata_message_proto = out.File
	file_chunkdata_message_proto_rawDesc = nil
	file_chunkdata_message_proto_goTypes = nil
	file_chunkdata_message_proto_depIdxs = nil
}
